### ISSUE TITLE
Please add a PSUtil to the standard set

### ISSUE THREAD

**Issue by peardox** [Embarcadero/P4D-Data-Sciences#11]
This is trivial in the extreme so I won't bother with a PR (PSUtil.pas + icon images below to save you 5 secs)

The reason for this addition being desirable is that PSUtil provides access to CPU, RAM and Virtual Memory stats which is obviously a highly desirable feature for any ML project as it will undoubtadly want as much of everything as possible so knowing what the system has makes sense.

The same kind of info is also useful for GPUs but PyTorch already has that partially covered (for NVIDIA - about to try M1)

Also I see the benefit of a simple blog article and this fits the aim of writing a P4D equivalent of slightly above 'Hello World' but useful enough to be worth writing so if it's in the main repo it's easier on the reader (and yes - I plan to write said article).

Note - there is also a Python wrapper for [CPU Features](https://github.com/google/cpu_features) but I found this to be too unstable to be cross-platform worthy. PSUtil is a nice and stable cross-platform alternative.

```

(********************************************************
 * Part of Python for Delphi - Data Sciences libraries  *
 *                                                      *
 * Copyright (c) 2022 by Embarcadero Technologies       *
 * Licensed under the MIT License                       *
 *                                                      *
 * For full license text and more information visit:    *
 * https://github.com/Embarcadero/P4D-Data-Sciences     *
 ********************************************************)


unit PSUtil;

interface

uses
  System.Classes, PyPackage, PyPackage.Model, PythonEngine;

type
  [ComponentPlatforms(pidAllPlatforms)]
  TPSUtil = class(TPyManagedPackage)
  private
    function AsVariant: variant;
  protected
    procedure Prepare(const AModel: TPyPackageModel); override;
    procedure ImportModule; override;
  public
    property np: variant read AsVariant;
  end;

implementation

uses
  System.Variants,
  PyPackage.Manager.ManagerKind,
  PyPackage.Manager.Pip,
  PyPackage.Manager.Conda;

{ TPSUtil }

function TPSUtil.AsVariant: variant;
begin
  Result := inherited;
end;

procedure TPSUtil.ImportModule;
begin
  MaskFPUExceptions(true);
  try
    inherited;
  finally
    MaskFPUExceptions(false);
  end;
end;

procedure TPSUtil.Prepare(const AModel: TPyPackageModel);
begin
  inherited;
  with AModel do begin
    PackageName := 'psutil';
    //NumPy from PIP
    PackageManagers.Add(
      TPyPackageManagerKind.pip,
      TPyPackageManagerPip.Create('psutil'));
    //NumPy from Conda
    PackageManagers.Add(
      TPyPackageManagerKind.conda,
      TPyPackageManagerConda.Create('psutil'));
  end;
end;

end.

```

Icon images
[images.zip](https://github.com/Embarcadero/P4D-Data-Sciences/files/9186695/images.zip)

**Comment by lmbelo** [comment]
@peardox send us a pull request. Thank you very much.

**Comment by peardox** [comment]
I didn't think it was worth it :)

OK - one PR coming up...

**Comment by lmbelo** [comment]
> I didn't think it was worth it :)
> 
> OK - one PR coming up...

It definitely does. Thank you very much :D

**Comment by peardox** [comment]
It's in my PR#14 so closing issue
