### ISSUE TITLE
OpenCV module import error

### ISSUE THREAD

**Issue by kartus42** [Embarcadero/P4D-Data-Sciences#6]
Hello gents,

very nice project you have started here!

I have tried to create a very simple OpenCV demo using several piece of code from PyTorch demo and I obtain a "Module not imported" error when I try to use my TOpenCV.
I have then explicitly added a `PyOpenCV.Import;` and now receive a 'FLOAT_DIVIDE_BY_ZERO" error.

I have attached the project producing the issue:
- setup button install python and openCV environnement
- test button load an image an play with it
[OpenCV.zip](https://github.com/Embarcadero/P4D-Data-Sciences/files/9041151/OpenCV.zip)

Thanks
Thomas

**Comment by lmbelo** [comment]
Hi @kartus42, 

Try this one:
[OpenCV.zip](https://github.com/Embarcadero/P4D-Data-Sciences/files/9041439/OpenCV.zip)

Regarding the float_divide_by_zero error, you need to mask fpu before importing OpenCV.

For more details:
https://github.com/Embarcadero/python4delphi/wiki/MaskFPUExceptions

**Comment by kartus42** [comment]
Hi @lmbelo,

it now works perfectly, appreciate your prompt reply.
I am totally new in python and its integration in Delphi, so probably more to come :).

Thanks

**Comment by lmbelo** [comment]
Feel free to contact us :D
